resolver: nightly-2021-06-21
packages:
- .

flags:
  hakyll:
    previewserver: false
    watchserver: false

extra-deps: 
- pandoc-2.14.0.3
- hakyll-images-1.0.1
- git: https://github.com/jaspervdj/hakyll.git
  commit: 6885325146aa46adf255c55de0e0345a0f84961e