name: GH-Pages

on:
  push:
    branches: [master]
  schedule:
    # Build the website twice a week, to keep it up-to-date
    # and keep the cache warm.
    # See https://crontab.guru/#0_5_*_*_0,4
    - cron: '0 5 * * 0,4'

jobs:
  build-and-deploy:
    if: contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # We need to fetch the whole history for the automatic 'last-updated'
        # functionality works as expected
        fetch-depth: 0

    - name: Install cabal/ghc
      uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: '9.6.3'
        cabal-version: '3.10.1.0'

    - name: Set PATH for cabal-installed executables
      run: |
        echo "$HOME/.cabal/bin" >> $GITHUB_PATH

    - name: Set Cabal options
      # Overwriting prevent cabal from raising an error when installing
      # an executable that is already present (because of caching)
      # Some of these options are superfluous for this workflow,
      # but I'm keeping them in sync with ci.yml so that caching is
      # shared
      run: |
        cabal update
        cabal user-config update -f -a "overwrite-policy: always"
        cabal user-config update -f -a "install-method: copy"
        cabal user-config update -f -a "split-sections: True"
        cabal user-config update -f -a "executable-stripping: True"

    - name: Cache cabal work
      uses: actions/cache@v2
      with:
        path: |
          dist-newstyle
          ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ hashFiles('cabal.*') }}-cabal-install

    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - uses: actions/cache@v2
      name: Cache Python build artifacts
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}

    - uses: actions/cache@v2
      name: Cache Rust build artifacts
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          tools/target
        key: ${{ runner.os }}-v2-${{ hashFiles('tools/Cargo.lock') }}

    - name: Build site compiler
      run: |
        cabal install -j --disable-optimization
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy wheel
        pip install -r requirements.txt
        
    - name: Download Bulma CSS
      env:
        bulma-version: 0.9.3
      run: |
        wget -c https://github.com/jgthms/bulma/releases/download/${{ env.bulma-version }}/bulma-${{ env.bulma-version }}.zip 
        unzip bulma-${{ env.bulma-version }}.zip -d sass

    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.4.7
      with:
        source: sass/style.scss
        destination: css/style.css
    
    - name: Generate banner
      run: |
        python scripts/mkbanner.py
    
    # Need to build twice because in the first build,
    # pandoc-plot creates files which are then routed
    # appropriately in the second build.
    # Also, we're disabling multicore behavior (+RTS -N1)
    # due to non-deterministic errors that can arise due to locks
    # on file reading. This is as of Hakyll version 4.16.2.0;
    # this problem may be resolved in the future.
    - name: Build website
      run: |
        personal-website clean +RTS -N1
        personal-website build +RTS -N1
        personal-website build +RTS -N1
  
    - name: Minify CSS and HTML
      run: |
        rustup update stable && rustup default stable
        cd tools 
        cargo build --bin minifier
        ./target/debug/minifier ../_rendered
        
    - name: Check internal links
      run: |
        personal-website check --internal-links

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        branch: gh-pages
        folder: _rendered
        clean: true
