name: GH-Pages

on:
  push:
    branches: [master]
  schedule:
    # Build the website twice a week, to keep it up-to-date
    # and keep the cache warm.
    # See https://crontab.guru/#0_5_*_*_0,4
    - cron: '0 5 * * 0,4'

jobs:
  build-and-deploy:
    if: contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack

    - uses: actions/setup-python@v2
      with:
        # Issues with dependencies using python 3.9+
        python-version: '3.8'

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}

    - name: Build compiler and dependencies
      run: |
        stack install
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.2.5
      with:
        source: sass/style.scss
        destination: css/style.css
    
    - name: Build website
      run: |
        stack exec -- personal-website clean
        stack exec -- personal-website build
        stack exec -- personal-website build
    
    - name: Check links
      run: |
        stack exec -- personal-website check --internal-links

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: decotret
        CLEAN: true