name: GH-Pages

on:
  push:
    branches: [master]
    paths-ignore:
      # Sass files are compiled in a separate workflow, which then commits changes.
      # These changes will trigger THIS workflow if needed.
      - "sass/*/**"
      - ".github/workflows/compile-sass.yml"
  schedule:
    # Build the website twice a week, to keep it up-to-date
    # and keep the cache warm.
    # See https://crontab.guru/#0_5_*_*_0,4
    - cron: '0 5 * * 0,4'

jobs:
  build-and-deploy:
    if: contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # We need to fetch the whole history for the automatic 'last-updated'
        # functionality works as expected
        fetch-depth: 0

    - name: Install cabal/ghc
      uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: '9.10.1'
        cabal-version: '3.12.1.0'

    - name: Set PATH for cabal-installed executables
      run: |
        echo "$HOME/.cabal/bin" >> $GITHUB_PATH

    - name: Set Cabal options
      # Overwriting prevent cabal from raising an error when installing
      # an executable that is already present (because of caching)
      # Some of these options are superfluous for this workflow,
      # but I'm keeping them in sync with ci.yml so that caching is
      # shared
      run: |
        cabal update
        cabal user-config update -f -a "overwrite-policy: always"
        cabal user-config update -f -a "install-method: copy"
        cabal user-config update -f -a "split-sections: True"
        cabal user-config update -f -a "executable-stripping: True"

    - name: Cache cabal work
      uses: actions/cache@v3
      with:
        path: |
          dist-newstyle
          ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ hashFiles('cabal.*') }}-cabal-install

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: actions/cache@v3
      name: Cache Python build artifacts
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}
    
    # We ensure that code used in posts still compile
    - name: Build all modules
      run: |
        cabal build all -j --disable-optimization

    - name: Build site compiler
      run: |
        cabal install -j --disable-optimization
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate banner
      run: |
        python scripts/mkbanner.py
    
    # Need to build twice because in the first build,
    # pandoc-plot creates files which are then routed
    # appropriately in the second build.
    - name: Build website
      run: |
        personal-website clean
        personal-website build
        personal-website build
        
    - name: Check internal links
      run: |
        personal-website check --internal-links

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        branch: gh-pages
        folder: _rendered
        clean: true
